/*const promise = new Promise((resolve, reject) => {
	setTimeout( () => {
		resolve('my promise resolve');
		reject('getting error');
	},2000);
});

console.log('before');

promise.then((data) => {
	console.log(data);
}).catch((error) =>{
	console.log(error);
});	


console.log('after');
*/